version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"  # Map container's 5432 to host's 5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: /app/entrypoint.sh localhost 5432 python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:mypassword@localhost:5433/mydatabase
    ports:
      - "8000:8000"
